# Tensors in Pytorch  
https://www.youtube.com/watch?v=jexkKugTg04&list=PLZbbT5o_s2xrfNyHZsM6ufI0iZENK9xgG&index=8



In [1]:
import torch
import numpy as np

In [4]:
t = torch.Tensor()
type(t)

torch.Tensor

## Tensor data types  
| Data type                | dtype                         | CPU tensor         | GPU tensor              |
|--------------------------|-------------------------------|--------------------|-------------------------|
| 32-bit floating point    | torch.float32 or torch.float  | torch.FloatTensor  | torch.cuda.FloatTensor  |
| 64-bit floating point    | torch.float64 or torch.double | torch.DoubleTensor | torch.cuda.DoubleTensor |
| 16-bit floating point    | torch.float16 or torch.half   | torch.HalfTensor   | torch.cuda.HalfTensor   |
| 8-bit integer (unsigned) | torch.uint8                   | torch.ByteTensor   | torch.cuda.ByteTensor   |
| 8-bit integer (signed)   | torch.int8                    | torch.CharTensor   | torch.cuda.CharTensor   |
| 16-bit integer (signed)  | torch.int16 or torch.short    | torch.ShortTensor  | torch.cuda.ShortTensor  |
| 32-bit integer (signed)  | torch.int32 or torch.int      | torch.IntTensor    | torch.cuda.IntTensor    |
| 64-bit integer (signed)  | torch.int64 or torch.long     | torch.LongTensor   | torch.cuda.LongTensor   |
| Boolean                  | torch.bool                    | torch.BoolTensor   | torch.cuda.BoolTensor   |  
***Note: Tensor operations can be only performed between tensors of the same type***

strided == how the data is stored in the memory

In [5]:
print(t.dtype)
print(t.device)
print(t.layout)

torch.float32
cpu
torch.strided


In [8]:
t1 = torch.tensor([1, 2, 3])
t2 = torch.tensor([1., 2., 3.])

In [9]:
t1.dtype

torch.int64

In [10]:
t2.dtype

torch.float32

In [11]:
t1 + t2

RuntimeError: expected type torch.FloatTensor but got torch.LongTensor

---
## Tensor devices

In [12]:
device = torch.device('cuda:0')
device

device(type='cuda', index=0)

***Note: Tensor operations can be only performed between tensors on the same device.***

In [13]:
t1 = torch.tensor([1, 2, 3])
t2 = t1.cuda()

In [14]:
t1.device

device(type='cpu')

In [15]:
t2.device

device(type='cuda', index=0)

In [16]:
t1 + t2

RuntimeError: expected type torch.LongTensor but got torch.cuda.LongTensor

---
## Tensor from data  
https://www.youtube.com/watch?v=AglLTlms7HU&list=PLZbbT5o_s2xrfNyHZsM6ufI0iZENK9xgG&index=9

In [17]:
data = np.array([1, 2, 3])
type(data)

numpy.ndarray

**Tensor**  
* class constructor  
* creates copy (more computationally expensive)

In [44]:
torch.Tensor(data)

tensor([0., 0., 0.])

**tensor**  
* factory function == accepts specific input, outputs specific object  
* creates copy (more computationally expensive)

In [19]:
torch.tensor(data)

tensor([1, 2, 3], dtype=torch.int32)

**as_tensor**  
* factory function 
* shares the same content as "data" (less expensive) - uses ine space in memory for both data and tensor  
* accepts more inputs, than from_numpy

In [27]:
torch.as_tensor(data)

tensor([1, 2, 3], dtype=torch.int32)

**from_numpy**  
* factory function  
* shares the same content as "data" (less expensive) - uses ine space in memory for both data and tensor  
* accepts only numpy inputs

In [28]:
torch.from_numpy(data)

tensor([1, 2, 3], dtype=torch.int32)

*Note: torch.tensor() is recommended for copy object. If it fits your need, always start with this option.  
torch.as_tensor() is recommended for shared object, if better performance is needed.*

---

In [34]:
torch.get_default_dtype()

torch.float32

*Note: Default dtype for Tensor class. Factory functions follow the dtype of input.*

In [35]:
torch.tensor(np.array([1, 2, 3]))

tensor([1, 2, 3], dtype=torch.int32)

In [36]:
torch.tensor(np.array([1., 2., 3.]))

tensor([1., 2., 3.], dtype=torch.float64)

In [37]:
torch.tensor(np.array([1, 2, 3]), dtype=torch.float64)

tensor([1., 2., 3.], dtype=torch.float64)

---

In [40]:
t1 = torch.Tensor(data)
t2 = torch.tensor(data)
t3 = torch.as_tensor(data)
t4 = torch.from_numpy(data)

In [42]:
data[0] = 0
data[1] = 0
data[2] = 0

In [43]:
print(t1)
print(t2)
print(t3)
print(t4)

tensor([1., 2., 3.])
tensor([1, 2, 3], dtype=torch.int32)
tensor([0, 0, 0], dtype=torch.int32)
tensor([0, 0, 0], dtype=torch.int32)


---
## Special types of tensors

In [29]:
torch.eye(2)

tensor([[1., 0.],
        [0., 1.]])

In [30]:
torch.zeros(2, 2)

tensor([[0., 0.],
        [0., 0.]])

In [31]:
torch.ones(2, 2)

tensor([[1., 1.],
        [1., 1.]])

In [32]:
torch.rand(2, 2)

tensor([[0.2390, 0.4324],
        [0.8056, 0.4415]])