# Tensor elements operations  
https://www.youtube.com/watch?v=QscEWm0QTRY&list=PLZbbT5o_s2xrfNyHZsM6ufI0iZENK9xgG&index=12

In [3]:
import torch
import numpy as np

In [4]:
t1 = torch.tensor([
    [1, 2],
    [3, 4]
], dtype=torch.float32)

t2 = torch.tensor([
    [9, 8],
    [7, 6]
], dtype=torch.float32)

*Note: Element operations between tensors can be performaed only when tensors have the same shape.*

---  
## math operations \+ \- \* /

In [5]:
t1 + t2

tensor([[10., 10.],
        [10., 10.]])

In [6]:
t1 + 2

tensor([[3., 4.],
        [5., 6.]])

In [7]:
t1 - 2

tensor([[-1.,  0.],
        [ 1.,  2.]])

In [8]:
t1 * 2

tensor([[2., 4.],
        [6., 8.]])

In [9]:
t1 / 2

tensor([[0.5000, 1.0000],
        [1.5000, 2.0000]])

In [10]:
t1.add(2)

tensor([[3., 4.],
        [5., 6.]])

In [11]:
t1.sub(2)

tensor([[-1.,  0.],
        [ 1.,  2.]])

In [12]:
t1.mul(2)

tensor([[2., 4.],
        [6., 8.]])

In [13]:
t1.div(2)

tensor([[0.5000, 1.0000],
        [1.5000, 2.0000]])

*Why does it work, when they do not have the same shape? Bcs of broadcasting.*

In [14]:
np.broadcast_to(2, t1.shape)

array([[2, 2],
       [2, 2]])

In [15]:
t1 + torch.tensor(np.broadcast_to(2, t1.shape), dtype=torch.float32)

tensor([[3., 4.],
        [5., 6.]])

---

In [16]:
t2 = torch.tensor([2, 4], dtype=torch.float32)

In [17]:
t1.shape

torch.Size([2, 2])

In [18]:
t2.shape

torch.Size([2])

In [19]:
t1 + t2

tensor([[3., 6.],
        [5., 8.]])

*is also broadcasted:*

In [20]:
np.broadcast_to(t2.numpy(), t1.shape)

array([[2., 4.],
       [2., 4.]], dtype=float32)

---  
## comparison operations

In [21]:
t = torch.tensor([
    [3, 2, 1],
    [6, 5, 4],
    [9, 8, 7]
], dtype=torch.float32)

In [22]:
t.eq(4)

tensor([[0, 0, 0],
        [0, 0, 1],
        [0, 0, 0]], dtype=torch.uint8)

*Note: 4 is also bordcasted.*

In [23]:
t.ge(4)

tensor([[0, 0, 0],
        [1, 1, 1],
        [1, 1, 1]], dtype=torch.uint8)

In [24]:
t.gt(4)

tensor([[0, 0, 0],
        [1, 1, 0],
        [1, 1, 1]], dtype=torch.uint8)

In [25]:
t.lt(4)

tensor([[1, 1, 1],
        [0, 0, 0],
        [0, 0, 0]], dtype=torch.uint8)

In [26]:
t.le(4)

tensor([[1, 1, 1],
        [0, 0, 1],
        [0, 0, 0]], dtype=torch.uint8)

---  
## math functions

In [27]:
t.abs()

tensor([[3., 2., 1.],
        [6., 5., 4.],
        [9., 8., 7.]])

In [28]:
t.sqrt()

tensor([[1.7321, 1.4142, 1.0000],
        [2.4495, 2.2361, 2.0000],
        [3.0000, 2.8284, 2.6458]])

In [29]:
t.neg()

tensor([[-3., -2., -1.],
        [-6., -5., -4.],
        [-9., -8., -7.]])

In [30]:
t.neg().abs()

tensor([[3., 2., 1.],
        [6., 5., 4.],
        [9., 8., 7.]])

---  
## reduction methods  
https://www.youtube.com/watch?v=K3lX3Cltt4c&list=PLZbbT5o_s2xrfNyHZsM6ufI0iZENK9xgG&index=13

In [52]:
t.sum()

tensor(45.)

In [53]:
t.sum().item()

45.0

In [32]:
t.numel()

9

In [33]:
t.sum().numel()

1

In [34]:
t.prod()

tensor(362880.)

In [63]:
t.prod().item()

362880.0

In [35]:
t.mean()

tensor(5.)

In [62]:
t.mean().item()

5.0

In [57]:
t.mean(dim=0).tolist()

[6.0, 5.0, 4.0]

In [60]:
import numpy as np
t.mean(dim=0).numpy()

array([6., 5., 4.], dtype=float32)

In [36]:
t.std()

tensor(2.7386)

In [61]:
t.std().item()

2.7386128902435303

*doest always return 1 element output.*

In [37]:
x = torch.tensor([
    [1, 1, 1, 1],
    [2, 2, 2, 2],
    [3, 3, 3, 3]
])

In [39]:
x.sum(dim=0)

tensor([6, 6, 6, 6])

In [40]:
x.sum(dim=1)

tensor([ 4,  8, 12])

---  
## argmax

In [42]:
y = torch.tensor([
    [1, 0, 0, 2],
    [0, 3, 3, 0],
    [4, 0, 0, 5]
], dtype=torch.float32)

In [44]:
y.max()

tensor(5.)

In [45]:
y.argmax()

tensor(11)

*index 11 in flatten form*

In [46]:
y.flatten()

tensor([1., 0., 0., 2., 0., 3., 3., 0., 4., 0., 0., 5.])

In [48]:
y.max(dim=0)

(tensor([4., 3., 3., 5.]), tensor([2, 1, 1, 2]))

*(tensor of max values, tensor of indexes)*

In [49]:
y.argmax(dim=0)

tensor([2, 1, 1, 2])

*tensor of indexes*

In [50]:
y.max(dim=1)

(tensor([2., 3., 5.]), tensor([3, 2, 3]))

In [51]:
y.argmax(dim=1)

tensor([3, 2, 3])