# Concat x stack  
https://www.youtube.com/watch?v=kF2AlpykJGY&list=PLZbbT5o_s2xrfNyHZsM6ufI0iZENK9xgG&index=28  
concat == join tensors along the same axis  
stack == join tensors along new axis  

---  
## Pytorch

In [1]:
import torch

In [2]:
t1 = torch.tensor([1, 1, 1])

In [3]:
t1.unsqueeze(dim=0)

tensor([[1, 1, 1]])

In [4]:
t1.unsqueeze(dim=1)

tensor([[1],
        [1],
        [1]])

In [5]:
print(t1.shape)
print(t1.unsqueeze(dim=0).shape)
print(t1.unsqueeze(dim=1).shape)

torch.Size([3])
torch.Size([1, 3])
torch.Size([3, 1])


---  

In [6]:
t1 = torch.tensor([1, 1, 1])
t2 = torch.tensor([2, 2, 2])
t3 = torch.tensor([3, 3, 3])

In [7]:
torch.cat((t1, t2, t3), dim=0)

tensor([1, 1, 1, 2, 2, 2, 3, 3, 3])

In [9]:
torch.stack((t1, t2, t3), dim=0)

tensor([[1, 1, 1],
        [2, 2, 2],
        [3, 3, 3]])

In [10]:
torch.stack((t1, t2, t3), dim=1)

tensor([[1, 2, 3],
        [1, 2, 3],
        [1, 2, 3]])

---  
## Tensorflow

In [11]:
import tensorflow as tf

C:\Users\Lukin\Anaconda3\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


In [12]:
t1 = tf.constant([1, 1, 1])
t2 = tf.constant([2, 2, 2])
t3 = tf.constant([3, 3, 3])

In [13]:
tf.concat((t1, t2, t3), axis=0)

<tf.Tensor: id=4, shape=(9,), dtype=int32, numpy=array([1, 1, 1, 2, 2, 2, 3, 3, 3])>

In [14]:
tf.stack((t1, t2, t3), axis=0)

<tf.Tensor: id=6, shape=(3, 3), dtype=int32, numpy=
array([[1, 1, 1],
       [2, 2, 2],
       [3, 3, 3]])>

In [15]:
tf.stack((t1, t2, t3), axis=1)

<tf.Tensor: id=8, shape=(3, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])>

---  
## Numpy

In [16]:
import numpy as np

In [17]:
t1 = np.array([1, 1, 1])
t2 = np.array([2, 2, 2])
t3 = np.array([3, 3, 3])

In [18]:
np.concatenate((t1, t2, t3), axis=0)

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

In [19]:
np.stack((t1, t2, t3), axis=0)

array([[1, 1, 1],
       [2, 2, 2],
       [3, 3, 3]])

In [20]:
np.stack((t1, t2, t3), axis=1)

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])