# fashion MNIST  
---  
## Build the model  
https://www.youtube.com/watch?v=k4jY9L8H89U&list=PLZbbT5o_s2xrfNyHZsM6ufI0iZENK9xgG&index=17  
https://www.youtube.com/watch?v=IKOHHItzukk&list=PLZbbT5o_s2xrfNyHZsM6ufI0iZENK9xgG&index=18  
https://www.youtube.com/watch?v=stWU37L91Yc&list=PLZbbT5o_s2xrfNyHZsM6ufI0iZENK9xgG&index=19  
https://youtube.com/watch?v=rcc86nXKwkw&list=PLZbbT5o_s2xrfNyHZsM6ufI0iZENK9xgG&index=20  
https://www.youtube.com/watch?v=MasG7tZj-hw&list=PLZbbT5o_s2xrfNyHZsM6ufI0iZENK9xgG&index=21  

In [1]:
import torch
import torch.nn as nn
import torch.nn.functional as F

torch.set_printoptions(linewidth=120)

In [2]:
class Network(nn.Module):
    def __init__(self):
        super(Network, self).__init__()
        self.conv1 = nn.Conv2d(in_channels=1, out_channels=6, kernel_size=5)
        self.conv2 = nn.Conv2d(in_channels=6, out_channels=12, kernel_size=5)
        
        # linear layer == fully connected layer == fc == dense layer
        self.fc1 = nn.Linear(in_features=12*4*4, out_features=120)
        self.fc2 = nn.Linear(in_features=120, out_features=60)
        self.out = nn.Linear(in_features=60, out_features=10)
        
    def forward(self, t):
        # (1) input layer:
        t = t
        
        # (2) hidden conv layer:
        t = self.conv1(t)
        t = F.relu(t)
        t = F.max_pool2d(t, kernel_size=2, stride=2)
        
        # (3) hidden conv layer:
        t = self.conv2(t)
        t = F.relu(t)
        t = F.max_pool2d(t, kernel_size=2, stride=2)
        
        # (4) hidden linear layer:
        t = t.reshape(-1, 12*4*4)
        # t = t.flatten()?
        t - self.fc1(t)
        t = F.relu(t)
        
        # (5) hidden linear layer:
        t - self.fc2(t)
        t = F.relu(t)
        
        # (6) output layer:
        t = self.out(t)
        # t = F.softmax(t, dim=1)
        
        return t

In [3]:
network = Network()
network

Network(
  (conv1): Conv2d(1, 6, kernel_size=(5, 5), stride=(1, 1))
  (conv2): Conv2d(6, 12, kernel_size=(5, 5), stride=(1, 1))
  (fc1): Linear(in_features=192, out_features=120, bias=True)
  (fc2): Linear(in_features=120, out_features=60, bias=True)
  (out): Linear(in_features=60, out_features=10, bias=True)
)

In [4]:
network.conv1

Conv2d(1, 6, kernel_size=(5, 5), stride=(1, 1))

In [5]:
network.conv1.weight

Parameter containing:
tensor([[[[-1.5060e-01, -8.8546e-02,  5.5302e-02,  1.4304e-01,  1.7649e-01],
          [ 1.1649e-01, -1.6447e-01,  1.8675e-01, -7.8628e-02, -1.0862e-01],
          [ 1.3782e-01,  7.0044e-02,  1.9636e-01,  3.1748e-02, -9.0024e-02],
          [ 8.8407e-03,  5.4654e-02,  1.2335e-01, -4.0481e-02,  1.8361e-01],
          [ 4.0780e-02,  1.7814e-01, -1.5411e-01, -2.8208e-02, -1.6344e-01]]],


        [[[-1.6326e-01,  1.0746e-01,  1.0033e-01, -8.6242e-02, -4.0223e-02],
          [-2.9542e-02, -1.9563e-01, -1.7717e-01,  3.2041e-02, -1.9875e-01],
          [ 1.6845e-01, -2.4584e-02,  1.9771e-01, -1.3722e-01, -1.6902e-01],
          [-3.2520e-02,  1.0664e-02, -2.3939e-02,  1.8899e-01, -6.1216e-02],
          [ 5.9301e-02, -1.0188e-01, -8.2890e-02, -1.4611e-01, -8.3138e-02]]],


        [[[-5.8667e-02,  7.8767e-02, -1.1670e-01, -3.2728e-02, -9.5333e-02],
          [-1.5661e-04, -3.5521e-02,  9.7196e-02,  1.1402e-01,  9.6104e-02],
          [ 2.4133e-03,  2.1635e-02, -1.2474e-

In [6]:
network.fc1.weight

Parameter containing:
tensor([[-0.0536, -0.0516, -0.0604,  ...,  0.0286,  0.0134, -0.0574],
        [ 0.0523,  0.0024,  0.0585,  ..., -0.0507,  0.0387, -0.0151],
        [ 0.0451,  0.0022, -0.0586,  ...,  0.0035,  0.0150,  0.0323],
        ...,
        [ 0.0657, -0.0088,  0.0625,  ...,  0.0312, -0.0117, -0.0459],
        [-0.0596, -0.0351, -0.0644,  ..., -0.0604, -0.0128,  0.0304],
        [ 0.0137, -0.0699, -0.0005,  ..., -0.0652,  0.0207, -0.0102]],
       requires_grad=True)

In [7]:
network.fc2.weight

Parameter containing:
tensor([[ 0.0751, -0.0012, -0.0633,  ..., -0.0573, -0.0768,  0.0757],
        [ 0.0616, -0.0805, -0.0694,  ..., -0.0311,  0.0347, -0.0373],
        [-0.0762,  0.0425,  0.0537,  ..., -0.0568, -0.0628, -0.0392],
        ...,
        [-0.0790, -0.0845,  0.0038,  ..., -0.0343,  0.0117, -0.0496],
        [ 0.0730, -0.0771,  0.0139,  ...,  0.0006,  0.0460, -0.0060],
        [ 0.0250,  0.0905, -0.0680,  ..., -0.0123, -0.0018,  0.0663]],
       requires_grad=True)

In [8]:
network.out.weight

Parameter containing:
tensor([[ 0.0913, -0.0990,  0.0658,  0.1040, -0.1012,  0.0126,  0.0630, -0.1162,
          0.0932,  0.1165,  0.0130,  0.0545, -0.0891,  0.0549,  0.0256,  0.0127,
         -0.0515,  0.0597,  0.0597,  0.1090,  0.0880,  0.0102,  0.0232,  0.0548,
          0.0400, -0.0967, -0.0641, -0.0472,  0.0405,  0.0919,  0.1025,  0.0409,
         -0.0185, -0.0004,  0.1115, -0.1084,  0.1146,  0.0265,  0.0940, -0.0909,
          0.0751, -0.1265,  0.1086,  0.0772, -0.1249,  0.0160,  0.0061, -0.0728,
          0.1113, -0.0632, -0.0641, -0.0673,  0.0163,  0.0242,  0.1017, -0.1059,
         -0.0419, -0.0101,  0.0190, -0.0739],
        [ 0.0778, -0.0936,  0.0869, -0.1031,  0.0996, -0.0502,  0.0973,  0.0717,
          0.0994,  0.0984,  0.1035, -0.0479, -0.0334,  0.0803,  0.0449,  0.0882,
          0.1137,  0.0061, -0.0299, -0.0440, -0.1033, -0.0868,  0.0325,  0.1043,
          0.0217, -0.0055,  0.0844, -0.0434,  0.0719,  0.1056,  0.0761, -0.0561,
          0.0640, -0.1003,  0.0826, -0.11

In [9]:
network.conv1.weight.shape

torch.Size([6, 1, 5, 5])

In [10]:
network.conv2.weight.shape

torch.Size([12, 6, 5, 5])

In [11]:
network.fc1.weight.shape

torch.Size([120, 192])

In [12]:
network.fc2.weight.shape

torch.Size([60, 120])

In [13]:
network.out.weight.shape

torch.Size([10, 60])

In [14]:
for param in network.parameters():
    print(param.shape)

torch.Size([6, 1, 5, 5])
torch.Size([6])
torch.Size([12, 6, 5, 5])
torch.Size([12])
torch.Size([120, 192])
torch.Size([120])
torch.Size([60, 120])
torch.Size([60])
torch.Size([10, 60])
torch.Size([10])


In [15]:
for name, param in network.named_parameters():
    print(f'{name} \t\t {param.shape}')

conv1.weight 		 torch.Size([6, 1, 5, 5])
conv1.bias 		 torch.Size([6])
conv2.weight 		 torch.Size([12, 6, 5, 5])
conv2.bias 		 torch.Size([12])
fc1.weight 		 torch.Size([120, 192])
fc1.bias 		 torch.Size([120])
fc2.weight 		 torch.Size([60, 120])
fc2.bias 		 torch.Size([60])
out.weight 		 torch.Size([10, 60])
out.bias 		 torch.Size([10])
