# fashion MNIST  
---  
## Prediction
https://www.youtube.com/watch?v=6vweQjouLEE&list=PLZbbT5o_s2xrfNyHZsM6ufI0iZENK9xgG&index=22  

In [2]:
import torch
import torch.nn as nn
import torch.nn.functional as F

import torchvision
import torchvision.transforms as transforms
# from torchvision import transforms

torch.set_printoptions(linewidth=120)

In [3]:
train_set = torchvision.datasets.FashionMNIST(
    root='data',
    train=True,
    download=True,
    transform=transforms.Compose([
        transforms.ToTensor()
    ])
)

In [4]:
class Network(nn.Module):
    def __init__(self):
        super(Network, self).__init__()
        self.conv1 = nn.Conv2d(in_channels=1, out_channels=6, kernel_size=5)
        self.conv2 = nn.Conv2d(in_channels=6, out_channels=12, kernel_size=5)
        
        # linear layer == fully connected layer == fc == dense layer
        self.fc1 = nn.Linear(in_features=12*4*4, out_features=120)
        self.fc2 = nn.Linear(in_features=120, out_features=60)
        self.out = nn.Linear(in_features=60, out_features=10)
        
    def forward(self, t):
        # (1) input layer:
        # t = t
        
        # (2) hidden conv layer:
        t = self.conv1(t)
        t = F.relu(t)
        t = F.max_pool2d(t, kernel_size=2, stride=2)
        
        # (3) hidden conv layer:
        t = self.conv2(t)
        t = F.relu(t)
        t = F.max_pool2d(t, kernel_size=2, stride=2)
        
        # (4) hidden linear layer:
        t = t.reshape(-1, 12*4*4)
        # t = t.flatten()
        t = self.fc1(t)
        t = F.relu(t)
        
        # (5) hidden linear layer:
        t = self.fc2(t)
        t = F.relu(t)
        
        # (6) output layer:
        t = self.out(t)
        #t = F.softmax(t, dim=1)
        
        return t

In [5]:
torch.set_grad_enabled(False)

*Note: turning off pytorch gradient tracking feature.*

In [6]:
network = Network()

In [7]:
sample = next(iter(train_set))

In [8]:
image, label = sample
image.shape

torch.Size([1, 28, 28])

In [9]:
image.unsqueeze(0).shape

torch.Size([1, 1, 28, 28])

In [10]:
pred = network(image.unsqueeze(0)) # batch size, color_channels, H, W

In [11]:
pred.shape

torch.Size([1, 10])

In [12]:
pred

tensor([[-0.1716,  0.1073, -0.0765, -0.0050,  0.0722, -0.0755, -0.0406, -0.0317,  0.0125, -0.0737]])

In [13]:
pred.argmax(dim=1)

tensor([1])

*prediction: bag*

In [14]:
label

9

*truth: Ankle Boot*

In [15]:
F.softmax(pred, dim=1)

tensor([[0.0864, 0.1142, 0.0950, 0.1021, 0.1102, 0.0951, 0.0985, 0.0994, 0.1039, 0.0953]])

*Note: each label has approx 10%.*

In [16]:
F.softmax(pred, dim=1).sum()

tensor(1.0000)