# fashion MNIST  
---  
## Prediction
https://www.youtube.com/watch?v=p1xZ2yWU1eo&list=PLZbbT5o_s2xrfNyHZsM6ufI0iZENK9xgG&index=23  
https://www.youtube.com/watch?v=cin4YcGBh3Q&list=PLZbbT5o_s2xrfNyHZsM6ufI0iZENK9xgG&index=24

In [28]:
import torch
import torch.nn as nn
import torch.nn.functional as F

import torchvision
import torchvision.transforms as transforms
# from torchvision import transforms

torch.set_printoptions(linewidth=120)

In [29]:
train_set = torchvision.datasets.FashionMNIST(
    root='data',
    train=True,
    download=True,
    transform=transforms.Compose([
        transforms.ToTensor()
    ])
)

In [30]:
class Network(nn.Module):
    def __init__(self):
        super(Network, self).__init__()
        self.conv1 = nn.Conv2d(in_channels=1, out_channels=6, kernel_size=5)
        self.conv2 = nn.Conv2d(in_channels=6, out_channels=12, kernel_size=5)
        
        # linear layer == fully connected layer == fc == dense layer
        self.fc1 = nn.Linear(in_features=12*4*4, out_features=120)
        self.fc2 = nn.Linear(in_features=120, out_features=60)
        self.out = nn.Linear(in_features=60, out_features=10)
        
    def forward(self, t):
        # (1) input layer:
        # t = t
        
        # (2) hidden conv layer:
        t = self.conv1(t)
        t = F.relu(t)
        t = F.max_pool2d(t, kernel_size=2, stride=2)
        
        # (3) hidden conv layer:
        t = self.conv2(t)
        t = F.relu(t)
        t = F.max_pool2d(t, kernel_size=2, stride=2)
        
        # (4) hidden linear layer:
        t = t.reshape(-1, 12*4*4)
        # t = t.flatten()
        t = self.fc1(t)
        t = F.relu(t)
        
        # (5) hidden linear layer:
        t = self.fc2(t)
        t = F.relu(t)
        
        # (6) output layer:
        t = self.out(t)
        #t = F.softmax(t, dim=1)
        
        return t

In [31]:
torch.set_grad_enabled(False)

*Note: turning off pytorch gradient tracking feature.*

In [32]:
network = Network()

In [33]:
data_loader = torch.utils.data.DataLoader(train_set, batch_size=10)

In [34]:
batch = next(iter(data_loader))

In [35]:
images, labels = batch

In [36]:
images.shape

torch.Size([10, 1, 28, 28])

In [37]:
labels.shape

torch.Size([10])

In [38]:
preds = network(images)

In [39]:
preds.shape

torch.Size([10, 10])

In [40]:
preds

tensor([[-0.1041,  0.0324,  0.0041, -0.0858,  0.1166,  0.0674,  0.0997,  0.0889,  0.0355,  0.1205],
        [-0.1088,  0.0360,  0.0013, -0.0777,  0.1174,  0.0645,  0.0909,  0.0851,  0.0254,  0.1145],
        [-0.1035,  0.0394,  0.0018, -0.0804,  0.1098,  0.0713,  0.0934,  0.0831,  0.0224,  0.1207],
        [-0.1057,  0.0410,  0.0030, -0.0810,  0.1115,  0.0659,  0.0931,  0.0801,  0.0213,  0.1154],
        [-0.0998,  0.0397,  0.0073, -0.0864,  0.1130,  0.0645,  0.0943,  0.0795,  0.0195,  0.1181],
        [-0.1050,  0.0387,  0.0023, -0.0751,  0.1102,  0.0661,  0.0906,  0.0822,  0.0244,  0.1195],
        [-0.0968,  0.0380,  0.0024, -0.0805,  0.1119,  0.0708,  0.1041,  0.0899,  0.0380,  0.1230],
        [-0.1028,  0.0346,  0.0024, -0.0766,  0.1117,  0.0620,  0.0936,  0.0847,  0.0319,  0.1126],
        [-0.0951,  0.0413,  0.0029, -0.0836,  0.1180,  0.0590,  0.1048,  0.0893,  0.0286,  0.1177],
        [-0.0965,  0.0356,  0.0043, -0.0870,  0.1213,  0.0587,  0.1091,  0.0952,  0.0389,  0.1143]])

In [41]:
preds.argmax(dim=1)

tensor([9, 4, 9, 9, 9, 9, 9, 9, 4, 4])

In [42]:
labels

tensor([9, 0, 0, 3, 0, 2, 7, 2, 5, 5])

In [43]:
preds.argmax(dim=1).eq(labels)

tensor([1, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=torch.uint8)

In [44]:
preds.argmax(dim=1).eq(labels).sum()

tensor(1)

In [46]:
def get_num_correct(preds, labels):
    return preds.argmax(dim=1).eq(labels).sum().item()

In [48]:
get_num_correct(preds, labels)

1